apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  labels:
    app: airflow
data:
  LOAD_EX: "n"
  EXECUTOR: Celery
  FERNET_KEY: "W0hMa-uUc_kA0vQGuuR7BTliVfreZ6KSdfxa87Asoak="
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_DB: airflow
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  REDIS_PASSWORD: redispass
